-- MySQL Script generated by MySQL Workbench
-- mar 04 nov 2014 20:02:03 CST
-- Model: New Model    Version: 1.0
SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema workflownotas
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `workflownotas` DEFAULT CHARACTER SET utf8 ;
USE `workflownotas` ;

-- -----------------------------------------------------
-- Table `workflownotas`.`catGrupos`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `workflownotas`.`catGrupos` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `nombre` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`id`))
ENGINE = MyISAM;


-- -----------------------------------------------------
-- Table `workflownotas`.`tblUsuarios`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `workflownotas`.`tblUsuarios` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `username` VARCHAR(15) NOT NULL,
  `nombre` VARCHAR(100) NOT NULL,
  `correo` VARCHAR(100) NOT NULL,
  `clave` VARCHAR(100) NOT NULL,
  `estatus` TINYINT(1) NOT NULL DEFAULT 0,
  `fecha_creacion` TIMESTAMP NULL DEFAULT CURRENT_TIMESTAMP,
  `grupos_id` INT NOT NULL,
  `last_login` DATETIME NULL DEFAULT NULL,
  `islogged` TINYINT(1) NULL DEFAULT 0,
  PRIMARY KEY (`id`),
  INDEX `fk_tblUsuarios_catGrupos1_idx` (`grupos_id` ASC))
ENGINE = MyISAM
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `workflownotas`.`catCaracteristicas`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `workflownotas`.`catCaracteristicas` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `nombre` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`id`))
ENGINE = MyISAM
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `workflownotas`.`catCaracteristicasTipo`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `workflownotas`.`catCaracteristicasTipo` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `nombre` VARCHAR(100) NOT NULL,
  `codigo` VARCHAR(3) NOT NULL,
  `caracteristicas_id` INT NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_catCaracteristicasTipo_caracteristicas1_idx` (`caracteristicas_id` ASC))
ENGINE = MyISAM
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `workflownotas`.`catRazones`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `workflownotas`.`catRazones` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `nombre` VARCHAR(100) NOT NULL,
  `codigo` VARCHAR(5) NOT NULL,
  `cuenta` VARCHAR(10) NOT NULL,
  `caracteristicasTipo_id` INT NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_catRazones_catCaracteristicasTipo1_idx` (`caracteristicasTipo_id` ASC))
ENGINE = MyISAM
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `workflownotas`.`catClientes`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `workflownotas`.`catClientes` (
  `codigo` VARCHAR(10) NOT NULL,
  `nombre` VARCHAR(255) NOT NULL,
  PRIMARY KEY (`codigo`))
ENGINE = MyISAM
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `workflownotas`.`catAnio`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `workflownotas`.`catAnio` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `anio` SMALLINT(4) NOT NULL,
  `impuesto` TINYINT(2) NOT NULL,
  PRIMARY KEY (`id`))
ENGINE = MyISAM
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `workflownotas`.`tblNotas`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `workflownotas`.`tblNotas` (
  `id` BIGINT NOT NULL AUTO_INCREMENT,
  `fecha_vencimiento` DATE NOT NULL,
  `fecha_creacion` TIMESTAMP NULL DEFAULT CURRENT_TIMESTAMP,
  `fecha_cierre` DATE NULL,
  `estatus` TINYINT(1) NOT NULL DEFAULT 0 COMMENT 'determina si la nota se encuentra en modo borrador o ya ha sido publicada',
  `revision` TINYINT NOT NULL DEFAULT 0 COMMENT 'revision sera un catalogo manejado por codigo donde:' /* comment truncated */ /*0 pendiente
1 aprobado
2 rechazado*/,
  `nivel_aprobacion` TINYINT NOT NULL DEFAULT 0 COMMENT 'determina el usuario aprobador que debe revisar' /* comment truncated */ /*1 - normal
2 - gerencial*/,
  `num_factura` VARCHAR(20) NULL,
  `comentario` TEXT NULL,
  `cancela_sustituye` TINYINT(1) NULL DEFAULT 0,
  `descripcion` VARCHAR(25) NULL,
  `tipo_orden` TINYINT NULL DEFAULT 0 COMMENT '7 u 8',
  `entrada_almacen` VARCHAR(20) NULL,
  `ordenCompra` VARCHAR(15) NULL,
  `usuarios_id` INT NOT NULL,
  `razones_id` INT NOT NULL,
  `clientes_codigo` VARCHAR(10) NOT NULL,
  `anio_id` INT NOT NULL DEFAULT 0,
  `indice` VARCHAR(10) NULL,
  `procesado` TINYINT(1) NULL DEFAULT 0,
  PRIMARY KEY (`id`),
  INDEX `fk_tblNotas_tblUsuarios1_idx` (`usuarios_id` ASC),
  INDEX `fk_tblNotas_catRazones1_idx` (`razones_id` ASC),
  INDEX `fk_tblNotas_catClientes1_idx` (`clientes_codigo` ASC),
  INDEX `fk_tblNotas_catAnio1_idx` (`anio_id` ASC))
ENGINE = MyISAM
AUTO_INCREMENT = 7000000000
DEFAULT CHARACTER SET = utf8
PACK_KEYS = DEFAULT;


-- -----------------------------------------------------
-- Table `workflownotas`.`tblHistorial`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `workflownotas`.`tblHistorial` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `descripcion` TEXT NOT NULL,
  `notas_id` BIGINT NOT NULL,
  `usuarios_id` INT NOT NULL,
  `fecha_creacion` TIMESTAMP NULL DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY (`id`),
  INDEX `fk_historial_notas1_idx` (`notas_id` ASC),
  INDEX `fk_tblHistorial_tblUsuarios1_idx` (`usuarios_id` ASC))
ENGINE = MyISAM
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `workflownotas`.`catEmpresas`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `workflownotas`.`catEmpresas` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `nombre` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`id`))
ENGINE = MyISAM
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `workflownotas`.`catMarcas`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `workflownotas`.`catMarcas` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `codigo` VARCHAR(10) NOT NULL,
  `marca` VARCHAR(50) NOT NULL,
  `es_gama` TINYINT NOT NULL DEFAULT 0,
  `cuenta_cooperacion` VARCHAR(10) NULL,
  `cuenta_descuento` VARCHAR(10) NULL,
  `empresas_id` INT NOT NULL,
  `color` VARCHAR(7) NULL,
  `identificador` VARCHAR(5) NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_catMarcas_catEmpresas1_idx` (`empresas_id` ASC))
ENGINE = MyISAM
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `workflownotas`.`catProductos`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `workflownotas`.`catProductos` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `codigo` VARCHAR(10) NOT NULL,
  `descripcion` VARCHAR(100) NOT NULL,
  `linea` VARCHAR(100) NULL,
  `fecha_adicion` TIMESTAMP NULL DEFAULT CURRENT_TIMESTAMP,
  `empresas_id` INT NOT NULL,
  `marcas_id` INT NOT NULL COMMENT 'identificador de carga',
  PRIMARY KEY (`id`),
  INDEX `fk_catProductos_catEmpresas1_idx` (`empresas_id` ASC),
  INDEX `fk_catProductos_catMarcas1_idx` (`marcas_id` ASC))
ENGINE = MyISAM
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `workflownotas`.`catSucursales`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `workflownotas`.`catSucursales` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `nombre` VARCHAR(100) NOT NULL,
  `editable` TINYINT NOT NULL DEFAULT 1,
  `codigo` VARCHAR(10) NULL,
  `clientes_codigo` VARCHAR(10) NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_catSucursales_catClientes1_idx` (`clientes_codigo` ASC))
ENGINE = MyISAM
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `workflownotas`.`catFlujos`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `workflownotas`.`catFlujos` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `nivel_aprobacion` TINYINT NOT NULL,
  `expresion` VARCHAR(20) NULL,
  `caracteristicasTipo_id` INT NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_catFlujos_catCaracteristicasTipo1_idx` (`caracteristicasTipo_id` ASC))
ENGINE = MyISAM
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `workflownotas`.`tblDocumentos`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `workflownotas`.`tblDocumentos` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `fecha_creacion` TIMESTAMP NULL DEFAULT CURRENT_TIMESTAMP,
  `archivo` VARCHAR(100) NOT NULL,
  `descripcion` VARCHAR(255) NOT NULL,
  `notas_id` BIGINT NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_tblDocumentos_tblNotas1_idx` (`notas_id` ASC))
ENGINE = MyISAM
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `workflownotas`.`catPermisos`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `workflownotas`.`catPermisos` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `permiso` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`id`))
ENGINE = MyISAM
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `workflownotas`.`tblNotas_has_productos`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `workflownotas`.`tblNotas_has_productos` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `notas_id` BIGINT NOT NULL,
  `productos_id` INT NOT NULL,
  `cantidad_piezas` SMALLINT NOT NULL DEFAULT 1,
  `num_lote` VARCHAR(15) NULL,
  `almacen` VARCHAR(10) NULL,
  `caducidad` VARCHAR(10) NULL,
  `aceptacion` TINYINT NULL DEFAULT 100,
  INDEX `fk_tblNotas_has_catProductos_catProductos1_idx` (`productos_id` ASC),
  INDEX `fk_tblNotas_has_catProductos_tblNotas1_idx` (`notas_id` ASC),
  PRIMARY KEY (`id`))
ENGINE = MyISAM
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `workflownotas`.`tblUsuarios_has_catEmpresas`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `workflownotas`.`tblUsuarios_has_catEmpresas` (
  `usuarios_id` INT NOT NULL,
  `empresas_id` INT NOT NULL,
  INDEX `fk_tblUsuarios_has_catEmpresas_catEmpresas1_idx` (`empresas_id` ASC),
  INDEX `fk_tblUsuarios_has_catEmpresas_tblUsuarios1_idx` (`usuarios_id` ASC))
ENGINE = MyISAM
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `workflownotas`.`tblUsuarios_has_catPermisos`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `workflownotas`.`tblUsuarios_has_catPermisos` (
  `usuarios_id` INT NOT NULL,
  `permisos_id` INT NOT NULL,
  INDEX `fk_tblUsuarios_has_catPermisos_catPermisos1_idx` (`permisos_id` ASC),
  INDEX `fk_tblUsuarios_has_catPermisos_tblUsuarios1_idx` (`usuarios_id` ASC))
ENGINE = MyISAM
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `workflownotas`.`tblProductosPrecio`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `workflownotas`.`tblProductosPrecio` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `precio` VARCHAR(20) NOT NULL,
  `productos_id` INT NOT NULL,
  `anio_id` INT NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_tblProductosPrecio_catProductos1_idx` (`productos_id` ASC),
  INDEX `fk_tblProductosPrecio_catAnio1_idx` (`anio_id` ASC))
ENGINE = MyISAM
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `workflownotas`.`catFacturas`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `workflownotas`.`catFacturas` (
  `id` BIGINT NOT NULL AUTO_INCREMENT,
  `orden_compra` VARCHAR(15) NOT NULL,
  `folio` VARCHAR(20) NOT NULL,
  `fecha` DATE NOT NULL,
  `monto` VARCHAR(20) NOT NULL,
  `codigo_producto` VARCHAR(10) NOT NULL,
  `descripcion_producto` VARCHAR(100) NOT NULL,
  `precio_unitario` VARCHAR(10) NOT NULL,
  `cantidad_piezas` SMALLINT NOT NULL,
  `costo_iva` VARCHAR(20) NOT NULL,
  `clientes_codigo` VARCHAR(10) NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_catFacturas_catClientes1_idx` (`clientes_codigo` ASC))
ENGINE = MyISAM
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `workflownotas`.`tblDescuentos`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `workflownotas`.`tblDescuentos` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `importe` VARCHAR(20) NOT NULL,
  `mes_aplicacion` TINYINT(2) NULL DEFAULT NULL,
  `notas_id` BIGINT NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_tblDescuentos_tblNotas1_idx` (`notas_id` ASC))
ENGINE = MyISAM;


-- -----------------------------------------------------
-- Table `workflownotas`.`catMarcas_has_descuentos`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `workflownotas`.`catMarcas_has_descuentos` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `importe` VARCHAR(20) NOT NULL,
  `marcas_id` INT NOT NULL,
  `descuentos_id` INT NOT NULL,
  INDEX `fk_tblNotas_has_catMarcas_catMarcas1_idx` (`marcas_id` ASC),
  PRIMARY KEY (`id`),
  INDEX `fk_tblNotas_has_catMarcas_tblDescuentos1_idx` (`descuentos_id` ASC))
ENGINE = MyISAM
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `workflownotas`.`tblCooperacion`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `workflownotas`.`tblCooperacion` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `importe` VARCHAR(20) NOT NULL,
  `mes_aplicacion` TINYINT(2) NOT NULL DEFAULT 1,
  `notas_id` BIGINT NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_tblCooperacion_tblNotas1_idx` (`notas_id` ASC))
ENGINE = MyISAM
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `workflownotas`.`catMarcas_has_cooperacion`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `workflownotas`.`catMarcas_has_cooperacion` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `importe` VARCHAR(20) NOT NULL,
  `marcas_id` INT NOT NULL,
  `cooperacion_id` INT NOT NULL,
  INDEX `fk_catMarcas_has_tblCooperacion_tblCooperacion1_idx` (`cooperacion_id` ASC),
  INDEX `fk_catMarcas_has_tblCooperacion_catMarcas1_idx` (`marcas_id` ASC),
  PRIMARY KEY (`id`))
ENGINE = MyISAM
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `workflownotas`.`tblUsuarios_has_catFlujos`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `workflownotas`.`tblUsuarios_has_catFlujos` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `usuarios_id` INT NOT NULL,
  `flujos_id` INT NOT NULL,
  INDEX `fk_tblUsuarios_has_catFlujos_catFlujos1_idx` (`flujos_id` ASC),
  INDEX `fk_tblUsuarios_has_catFlujos_tblUsuarios1_idx` (`usuarios_id` ASC),
  PRIMARY KEY (`id`))
ENGINE = MyISAM
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `workflownotas`.`tblNotas_has_catFlujos`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `workflownotas`.`tblNotas_has_catFlujos` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `notas_id` BIGINT NOT NULL,
  `flujos_id` INT NOT NULL,
  INDEX `fk_tblNotas_has_catFlujos_catFlujos1_idx` (`flujos_id` ASC),
  INDEX `fk_tblNotas_has_catFlujos_tblNotas1_idx` (`notas_id` ASC),
  PRIMARY KEY (`id`))
ENGINE = MyISAM
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `workflownotas`.`catClientes_has_catEmpresas`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `workflownotas`.`catClientes_has_catEmpresas` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `clientes_codigo` VARCHAR(10) NOT NULL,
  `empresas_id` INT NOT NULL,
  INDEX `fk_catClientes_has_catEmpresas_catEmpresas1_idx` (`empresas_id` ASC),
  INDEX `fk_catClientes_has_catEmpresas_catClientes1_idx` (`clientes_codigo` ASC),
  PRIMARY KEY (`id`))
ENGINE = MyISAM
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `workflownotas`.`tblUsuarios_has_catClientes`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `workflownotas`.`tblUsuarios_has_catClientes` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `usuarios_id` INT NOT NULL,
  `clientes_codigo` VARCHAR(10) NOT NULL,
  INDEX `fk_tblUsuarios_has_catClientes_catClientes1_idx` (`clientes_codigo` ASC),
  INDEX `fk_tblUsuarios_has_catClientes_tblUsuarios1_idx` (`usuarios_id` ASC),
  PRIMARY KEY (`id`))
ENGINE = MyISAM
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `workflownotas`.`tblAprobadores_has_solicitantes`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `workflownotas`.`tblAprobadores_has_solicitantes` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `aprobador` INT NOT NULL,
  `solicitante` INT NOT NULL,
  INDEX `fk_tblUsuarios_has_tblUsuarios_tblUsuarios2_idx` (`solicitante` ASC),
  INDEX `fk_tblUsuarios_has_tblUsuarios_tblUsuarios1_idx` (`aprobador` ASC),
  PRIMARY KEY (`id`))
ENGINE = MyISAM
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `workflownotas`.`catDescuentoClientes`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `workflownotas`.`catDescuentoClientes` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `codigo` VARCHAR(5) NOT NULL,
  `todas_nopfd` VARCHAR(5) NOT NULL,
  `pfd_notrev` VARCHAR(5) NOT NULL,
  `todas_trev` VARCHAR(5) NOT NULL,
  `clientes_codigo` VARCHAR(10) NOT NULL,
  `anio_id` INT NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_CatDescuentoClientes_catClientes1_idx` (`clientes_codigo` ASC),
  INDEX `fk_catDescuentoClientes_catAnio1_idx` (`anio_id` ASC))
ENGINE = MyISAM;


-- -----------------------------------------------------
-- Table `workflownotas`.`tblProcesamiento`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `workflownotas`.`tblProcesamiento` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `tipo` VARCHAR(45) NOT NULL COMMENT '- factura' /* comment truncated */ /*- precio*/,
  `archivo` VARCHAR(100) NOT NULL,
  `fecha` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY (`id`))
ENGINE = MyISAM
DEFAULT CHARACTER SET = utf8
COMMENT = 'Almacena registro de todos los archivos procesados de forma automatica';


-- -----------------------------------------------------
-- Table `workflownotas`.`catClientes_has_tblProductosPrecio`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `workflownotas`.`catClientes_has_tblProductosPrecio` (
  `catClientes_codigo` VARCHAR(10) NOT NULL,
  `tblProductosPrecio_id` INT NOT NULL,
  INDEX `fk_catClientes_has_tblProductosPrecio_tblProductosPrecio1_idx` (`tblProductosPrecio_id` ASC),
  INDEX `fk_catClientes_has_tblProductosPrecio_catClientes1_idx` (`catClientes_codigo` ASC))
ENGINE = MyISAM
DEFAULT CHARACTER SET = utf8;

ALTER TABLE `workflownotas`.`catClientes_has_tblProductosPrecio`
ADD COLUMN `id` INT(11) NOT NULL AUTO_INCREMENT FIRST,
ADD PRIMARY KEY (`id`)


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
